# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2GWW70p0bUEDoff9EkoMiRwBXIFWWp_
"""

import torch
from torch import nn

# =========================
# Model select
# =========================
ResNet44=ResNet(N=7).to(device)
ResNet44.apply(init_weights)
#PlainNet44=PlainNet(N=7).to(device)
#PlainNet44.apply(init_weights)

model = ResNet44
#model = PlainNet44

# =========================
# Accuracy and loss list
# =========================
Res_train_acc_list = []
Res_test_acc_list = []
Res_train_loss_list = []

#Plain_train_acc_list = []
#Plain_test_acc_list = []
#Plain_train_loss_list = []

# =========================
# Optimizer and hyper-parameters
# =========================
loss_fn = nn.CrossEntropyLoss()
lr = 1e-3
weight_decay = 1e-4
optimizer = torch.optim.Adam(model.parameters(),lr=lr,weight_decay = weight_decay)
epochs = 50

# =========================
# Train
# =========================
for epoch in range(epochs):
  print(f"-----epoch {epoch+1}-----")
  train_loop(train_dataloader,model,Res_train_acc_list,Res_train_loss_list)
  test_loop(test_dataloader,model,Res_test_acc_list)

  #train_loop(train_dataloader,model,Plain_train_acc_list,Plain_train_loss_list)
  #test_loop(test_dataloader,model,Plain_test_acc_list)